os: linux
dist: bionic
language: python
python: 3.7

services:
  - docker

branches:
  only:
    - master
    - /^v?\d+(\.\d+)*$/

env:
  matrix:
    - QGIS_VERSION=3.4
    - QGIS_VERSION=3.10
    - QGIS_VERSION=3.16

install:
  - mkdir .local
  - mkdir .cache
script:
  - >
    docker run
    --rm --name qgis-server
    -u $(id -u)
    -v ${TRAVIS_BUILD_DIR}/.cache:/.cache
    -e PIP_CACHE_DIR=/.cache
    -w /src/tests
    -e PYTEST_ADDOPTS=""
    -v ${TRAVIS_BUILD_DIR}:/src
    -v ${TRAVIS_BUILD_DIR}/.local:/.local
    3liz/qgis-platform:${QGIS_VERSION}
    ./run-tests.sh

jobs:
  include:
    - stage: Deploy
      if: tag IS present
      env: # no environment variables - overwrite with empty to remove matrix
      name: Create release, plugins.qgis.org
      install:
        - pip3 install qgis-plugin-ci==1.8.4
      before_deploy:
        - export RELEASE_TITLE=${TRAVIS_TAG:1}
        - qgis-plugin-ci changelog $TRAVIS_TAG > ../release.md
        - cat ../release.md
      script:
        - qgis-plugin-ci -v
